#!/usr/bin/env python3
"""Regenerate backend/app/collection/trusted_collectors.json from the collector scripts.

    python scripts/update-collector-hashes.py          # rewrite the file
    python scripts/update-collector-hashes.py --check  # exit 1 if it is out of date

Each collector is listed with the SHA-256 of its LF and CRLF forms: git checks the PowerShell
script out with CRLF (.gitattributes) while a raw download of the same blob has LF, and the
collector reports the hash of the bytes it runs from.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "backend" / "app" / "collection" / "trusted_collectors.json"
COLLECTORS = {
    "collector/collect_linux.py": ("dfirbench-collect-linux", r'^VERSION = "([^"]+)"'),
    "collector/collect-windows.ps1": (
        "dfirbench-collect-windows",
        r"^\$CollectorVersion = '([^']+)'",
    ),
}


def build() -> dict[str, object]:
    items = []
    for rel, (name, pattern) in COLLECTORS.items():
        raw = (ROOT / rel).read_bytes()
        lf = raw.replace(b"\r\n", b"\n")
        crlf = lf.replace(b"\n", b"\r\n")
        match = re.search(pattern, lf.decode("utf-8"), re.MULTILINE)
        if match is None:
            raise SystemExit(f"no version found in {rel}")
        for eol, data in (("lf", lf), ("crlf", crlf)):
            items.append(
                {
                    "name": name,
                    "version": match.group(1),
                    "file": rel,
                    "eol": eol,
                    "sha256": hashlib.sha256(data).hexdigest(),
                }
            )
    return {
        "comment": "Generated by scripts/update-collector-hashes.py; do not edit by hand.",
        "collectors": items,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = json.dumps(build(), indent=2) + "\n"
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{OUT} is out of date; run scripts/update-collector-hashes.py", file=sys.stderr)
            return 1
        print("trusted collector hashes are current")
        return 0
    OUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
