"""Collector trust (guide 9.2 rule 4): the manifest reports the collector's own SHA-256; the server
compares it with a list kept OUTSIDE the database.

* ``trusted_collectors.json`` next to this module: the released collector scripts (regenerated by
  ``scripts/update-collector-hashes.py``; a unit test keeps it in sync with ``collector/``).
* ``COLLECTOR_TRUSTED_HASHES_PATH`` (optional): an operator-maintained file in the same format, for
  locally signed or modified collectors. Keep it on a read-only mount.

An unknown hash is reported (``collector_unverified``) but does not block ingest: field teams
legitimately adapt collectors. The bundle's own integrity rests on the manifest hashes and the
custody chain, not on this check.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import structlog

from app.collection.manifest import TriageManifest

log = structlog.stdlib.get_logger("dfirbench.collection.trust")

PACKAGED = Path(__file__).with_name("trusted_collectors.json")
_HEX64 = re.compile(r"^[0-9a-f]{64}$")


def _read(path: Path) -> dict[str, dict[str, str]]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, dict[str, str]] = {}
    for item in raw.get("collectors", []):
        digest = str(item.get("sha256", "")).lower()
        if not _HEX64.fullmatch(digest):
            continue
        out[digest] = {
            "name": str(item.get("name", "")),
            "version": str(item.get("version", "")),
            "file": str(item.get("file", "")),
        }
    return out


def load_trusted_collectors(extra_path: str | None = None) -> dict[str, dict[str, str]]:
    trusted = _read(PACKAGED)
    if extra_path:
        try:
            trusted.update(_read(Path(extra_path)))
        except (OSError, ValueError, AttributeError) as exc:
            log.error("collector_trust_file_unreadable", error=type(exc).__name__)
    return trusted


def collector_trust(manifest: TriageManifest, trusted: dict[str, dict[str, str]]) -> dict[str, Any]:
    reported = manifest.collector.sha256
    if reported is None:
        return {"status": "no_hash", "name": manifest.collector.name}
    known = trusted.get(reported)
    if known is None:
        return {"status": "unknown", "sha256": reported, "name": manifest.collector.name}
    if known["name"] != manifest.collector.name or known["version"] != manifest.collector.version:
        return {
            "status": "name_mismatch",
            "sha256": reported,
            "name": manifest.collector.name,
            "known_as": f"{known['name']} {known['version']}",
        }
    return {"status": "trusted", "sha256": reported, "name": known["name"], "file": known["file"]}
